### ISSUE TITLE
Build fails to deploy - Error: 'acorn' is not a registered wp command. See 'wp help' for available commands.

### ISSUE THREAD

**Issue by maxray** [wpengine/example-sage-theme#22]
When using this repo to set up a Sage theme publishing to a WPE staging server the deploy fails with the error:

Error: 'acorn' is not a registered wp command. See 'wp help' for available commands.

I altered the action.yml slightly as the build was initially failing as Github was uing php8.0 not 8.2

action.yml attached (renamed to txt) 
build logs attached. 

[action.txt](https://github.com/user-attachments/files/16470847/action.txt)

[logs_26730970726.zip](https://github.com/user-attachments/files/16470852/logs_26730970726.zip)

Spoke to WPE support for quite a while who eventually said would be better to raise as an issue here.

Ideally would be using Bedrock/Sage on WPEngine but at this point am happy to sacrifice that if I can get sage10 theme building.

**Comment by marcywdev** [comment]
Hello, I experienced this same issue. The [Acorns documentation](https://roots.io/acorn/docs/installation/#booting-acorn) mentions "Acorn must be booted in order to use it." To resolve this, I updated the `post-deploy.sh` script to ensure the theme is active before running the Acorn cache clear command. Here is the updated `post-deploy.sh` which got this working for me:

```bash
#!/bin/bash

# Check if the theme is already active, and activate it if not
if ! wp theme is-active your-roots-theme-name-here; then
    echo "Activating the theme..."
    wp theme activate your-roots-theme-name-here
else
    echo "The theme is already active."
fi

# Check if the wp acorn command is available
if wp acorn &> /dev/null; then
    echo "wp acorn command is available"

    # Run wp acorn view:cache command
    echo "Running wp acorn view:cache..."
     if ! wp acorn view:cache; then
        echo "Failed to cache views" >&2
        exit 1
     fi
else
    echo "wp acorn command is not available"
fi
``` 

I also updated the `action.yml` (using `dev.yml` here for dev WPEngine environment) to use later versions of actions and improve Composer handling:
```yaml
name: Deploy to WPEngine - DEV
env:
  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
  WPE_INSTALL_NAME: your-wp-install-name
  THEME_NAME: your-roots-theme-name-here
on:
  push:
    branches:
      - dev
jobs:
  js-build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the git repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install js/css dependencies
        uses: borales/actions-yarn@v4
        with:
          dir: wp-content/themes/${{ env.THEME_NAME }}
          cmd: install

      - name: Build js/css
        uses: borales/actions-yarn@v4
        with:
          dir: wp-content/themes/${{ env.THEME_NAME }}
          cmd: build

      - name: Clean up node modules (not needed to deploy)
        run: rm -rf wp-content/themes/${{ env.THEME_NAME }}/node_modules

      - name: Deploy to WPE
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          SCRIPT: post-deploy.sh
          WPE_ENV: ${{ env.WPE_INSTALL_NAME }}

  php-build:
    runs-on: ubuntu-latest
    container: php:8.1-alpine
    steps:

      - name: Check out the git repo
        uses: actions/checkout@v4

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Install PHP dependencies
        run: |
          mv composer.phar wp-content/themes/${{ env.THEME_NAME }}/composer.phar
          cd wp-content/themes/${{ env.THEME_NAME }}
          
          # Check if composer.phar exists before running install
          if [ -f composer.phar ]; then
            echo "composer.phar found, proceeding with install."
            php composer.phar install
          else
            echo "composer.phar not found, cannot proceed with install."
          fi

          # Attempt to remove composer.phar
          if [ -f composer.phar ]; then
            rm composer.phar
            echo "composer.phar removed successfully."
          else
            echo "composer.phar not found, nothing to remove."
          fi

          # Verify removal
          if [ -f composer.phar ]; then
            echo "composer.phar still exists after removal attempt."
          else
            echo "composer.phar removed successfully."
          fi

      - name: Deploy to wpengine.com
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          SCRIPT: post-deploy.sh
          WPE_ENV: ${{ env.WPE_INSTALL_NAME }}
```
